#!/usr/bin/env python3
"""Generate spdif-policy.h from policy.py, which is the single owner of the decision.

`make check` regenerates into a temporary file and diffs, so a hand-edited header fails the build
rather than quietly diverging from the table it is supposed to mirror.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import policy  # noqa: E402

H = pathlib.Path(__file__).parent / "spdif-policy.h"

rows = []
for code, name, _disp, _codec, why in policy.TYPES:
    disp = policy.disposition(code).upper()
    codec = policy.codec_name(code)
    codec_c = f'"{codec}"' if codec else "NULL"
    rows.append(f'    {{ 0x{code:02X}, "{name}", SPDIF_{disp}, {codec_c} }},'
                f'{"":<{max(0, 46 - len(name) - len(codec_c))}} /* {why} */')

out = f'''/* GENERATED by gen-policy.py from policy.py -- DO NOT EDIT.
 *
 * policy.py is the single owner of which payload types this build decodes, and why. It is a
 * licensing decision rather than a technical fact; edit it there, run `make policy`, and commit
 * both. `make check` fails if this file has drifted from it.
 *
 * The safety rule this encodes: anything not SPDIF_DECODE is dropped, never emitted as audio. A raw
 * bitstream burst read as linear PCM is full-scale white noise. SPDIF_UNKNOWN is therefore a
 * rejection and not a fallback -- a type nobody considered gets silence.
 *
 * DECODE_DTS was {policy.DECODE_DTS} when this was generated.
 */
#pragma once

typedef enum {{
    SPDIF_DECODE,     /* hand the payload to libavcodec */
    SPDIF_SILENT,     /* valid framing, no payload: NULL and PAUSE. Not a fault */
    SPDIF_REJECT,     /* recognised, deliberately not decoded -> dropped */
    SPDIF_UNKNOWN,    /* not recognised -> dropped. The fail-safe default */
}} spdif_disposition_t;

typedef struct {{
    unsigned            data_type;   /* Pc & 0x1F */
    const char         *name;
    spdif_disposition_t disposition;
    const char         *codec;       /* libavcodec decoder name, or NULL */
}} spdif_policy_t;

static const spdif_policy_t SPDIF_POLICY[] = {{
{chr(10).join(rows)}
}};

#define SPDIF_POLICY_N (sizeof(SPDIF_POLICY) / sizeof(SPDIF_POLICY[0]))

static inline const spdif_policy_t *spdif_lookup(unsigned data_type)
{{
    for (unsigned i = 0; i < SPDIF_POLICY_N; i++)
        if (SPDIF_POLICY[i].data_type == (data_type & 0x1Fu))
            return &SPDIF_POLICY[i];
    return NULL;   /* caller treats NULL as SPDIF_UNKNOWN: dropped */
}}
'''

if len(sys.argv) > 1 and sys.argv[1] == "--stdout":
    sys.stdout.write(out)
else:
    H.write_text(out)
    print(f"wrote {H}")
