/* GENERATED by gen-policy.py from policy.py -- DO NOT EDIT.
 *
 * policy.py is the single owner of which payload types this build decodes, and why. It is a
 * licensing decision rather than a technical fact; edit it there, run `make policy`, and commit
 * both. `make check` fails if this file has drifted from it.
 *
 * The safety rule this encodes: anything not SPDIF_DECODE is dropped, never emitted as audio. A raw
 * bitstream burst read as linear PCM is full-scale white noise. SPDIF_UNKNOWN is therefore a
 * rejection and not a fallback -- a type nobody considered gets silence.
 *
 * DECODE_DTS was False when this was generated.
 */
#pragma once

typedef enum {
    SPDIF_DECODE,     /* hand the payload to libavcodec */
    SPDIF_SILENT,     /* valid framing, no payload: NULL and PAUSE. Not a fault */
    SPDIF_REJECT,     /* recognised, deliberately not decoded -> dropped */
    SPDIF_UNKNOWN,    /* not recognised -> dropped. The fail-safe default */
} spdif_disposition_t;

typedef struct {
    unsigned            data_type;   /* Pc & 0x1F */
    const char         *name;
    spdif_disposition_t disposition;
    const char         *codec;       /* libavcodec decoder name, or NULL */
} spdif_policy_t;

static const spdif_policy_t SPDIF_POLICY[] = {
    { 0x00, "NULL", SPDIF_SILENT, NULL },                                       /* valid framing, no payload -- not a fault */
    { 0x01, "AC3", SPDIF_DECODE, "ac3" },                                       /* core patents expired; what a TV actually sends */
    { 0x03, "PAUSE", SPDIF_SILENT, NULL },                                      /* valid framing, no payload -- not a fault */
    { 0x04, "MPEG1_L1", SPDIF_DECODE, "mp1" },                                  /* expired */
    { 0x05, "MPEG1_L2", SPDIF_DECODE, "mp2" },                                  /* expired */
    { 0x06, "MPEG2_EXT", SPDIF_REJECT, NULL },                                  /* multichannel MPEG-2; unclear, and never seen here */
    { 0x07, "MPEG2_AAC", SPDIF_REJECT, NULL },                                  /* licensing pools still active */
    { 0x08, "MPEG2_L1_LSF", SPDIF_DECODE, "mp1" },                              /* expired */
    { 0x09, "MPEG2_L2_LSF", SPDIF_DECODE, "mp2" },                              /* expired */
    { 0x0A, "MPEG2_L3_LSF", SPDIF_DECODE, "mp3" },                              /* expired */
    { 0x0B, "DTS1", SPDIF_REJECT, NULL },                                       /* see DECODE_DTS -- owner's decision */
    { 0x0C, "DTS2", SPDIF_REJECT, NULL },                                       /* see DECODE_DTS -- owner's decision */
    { 0x0D, "DTS3", SPDIF_REJECT, NULL },                                       /* see DECODE_DTS -- owner's decision */
    { 0x0E, "ATRAC", SPDIF_REJECT, NULL },                                      /* Sony; obscure, unassessed */
    { 0x0F, "ATRAC3", SPDIF_REJECT, NULL },                                     /* Sony; obscure, unassessed */
    { 0x11, "DTS_HD", SPDIF_REJECT, NULL },                                     /* live patents; cannot fit down optical */
    { 0x13, "WMAPRO", SPDIF_REJECT, NULL },                                     /* Microsoft */
    { 0x15, "EAC3", SPDIF_REJECT, NULL },                                       /* live patents; cannot fit down optical */
    { 0x16, "MAT", SPDIF_REJECT, NULL },                                        /* Dolby TrueHD; live patents */
};

#define SPDIF_POLICY_N (sizeof(SPDIF_POLICY) / sizeof(SPDIF_POLICY[0]))

static inline const spdif_policy_t *spdif_lookup(unsigned data_type)
{
    for (unsigned i = 0; i < SPDIF_POLICY_N; i++)
        if (SPDIF_POLICY[i].data_type == (data_type & 0x1Fu))
            return &SPDIF_POLICY[i];
    return NULL;   /* caller treats NULL as SPDIF_UNKNOWN: dropped */
}
